### ISSUE TITLE
Main Drawer

### ISSUE THREAD

**Issue by Jnolcox** [CUNYTech/CityBikeApp#3]
In your main drawer, you have a list of menu items;

- Map O
- History O
- Explore
- Settings O
- Plan O
- About Us

For continuity of aesthetics of your menu, it should be reorganized as follows;

- Map O
- History O
- Plan O
- Settings O
- Explore
- About Us

Since the first 4 have radio buttons. You could also alleviate this by removing the radio buttons on all of them and replacing it with the right arrow icon.

**Comment by Francely** [comment]
Appreciate the feedback, but I guess it depends on what phone you are using because on the phone I test it on, there are no radio buttons

**Comment by Jnolcox** [comment]
Its an Android only application I believe. This was on a [Nexus 5](http://imgur.com/a/tZxMf)

**Comment by jodz959** [comment]
Hi John,

I'll look into that, thanks for the feedback.

Jody

**Comment by Francely** [comment]
![screenshot_2017-03-21-23-03-02_resized](https://cloud.githubusercontent.com/assets/3875033/24180427/44b127d8-0e8b-11e7-9cbd-9f746381f5f5.png)

**Comment by Francely** [comment]
different versions of android might result in different results

**Comment by Jnolcox** [comment]
Interesting. I'll close it. I forked since I like what you're doing and want to extrapolate on it.
